name: commando24
description: Inspired by Commando as seen on the C64 in 1985

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0

environment:
  sdk: ^3.3.0

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.1.1
  collection: ^1.19.0
  dart_extensions_methods: ^2.0.0
  flame: ^1.28.1
  flame_audio: ^2.11.5
  flame_forge2d: ^0.19.0+1
  flame_tiled: ^3.0.2
  flutter_animate: ^4.5.2
  flutter_soloud: ^3.1.8
  gamepads: ^0.1.7
  image: ^4.5.4
  kart: ^1.0.8
  kt_dart: ^1.1.0
  list_operators: ^0.5.0
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  signals_core: ^5.2.0
  stream_transform: ^2.1.0
  supercharged: ^2.1.1
  web: ^1.1.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15

flutter:
  assets:
    - assets/audio/
    - assets/audio/music/
    - assets/audio/sound/
    - assets/data/
    - assets/fonts/
    - assets/images/
    - assets/images/fonts/
    - assets/tiles/
